--!strict
local Scheme = {
    --Per life
    Current_Kills = "NON_NULL NUMBER 0",
    Current_Cash = "NON_NULL NUMBER 0",
    Current_Healed = "NON_NULL NUMBER 0",
    Current_Robberies = "NON_NULL NUMBER 0",

    --Per Save slot
    Total_Gun_Kills = "NON_NULL NUMBER 0",
    Total_Melee_Kills = "NON_NULL NUMBER 0",
    Total_Kills = "NON_NULL NUMBER 0",
    Total_Cash = "NON_NULL NUMBER 0",
    Total_Damage = "NON_NULL NUMBER 0",
    Total_Healed = "NON_NULL NUMBER 0",
    Total_Spent_Cash = "NON_NULL NUMBER 0",
    Total_Robberies = "NON_NULL NUMBER 0",
}

return Scheme